### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by onokumus**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Looks great so far! But we'll need to make sure that this passes all of the unit tests before merging. If devDependencies cause the tests to fail they will need to be removed or changed. 

fwiw, I know it seems ridiculous to support older versions of node.js, but there are scenarios where people are unable to take advantage of newer versions of node, and for the time being, I'd like to be as compatible as possible. 

thanks!

**Comment by jonschlinkert** [comment]
@doowb any feedback?

**Comment by doowb** [comment]
> But we'll need to make sure that this passes all of the unit tests before merging. 

I agree with this. I think we can make this possible by not having a `prepublish` script in `package.json` and instead, we run the build for the other distributions when we're actually going to publish. This will let the older versions of node use the source code directly when running the tests and `rollup` can still be used since it will only be run locally.

**Comment by onokumus** [comment]
Do I remove old versions of node.js for unit tests?

**Comment by jonschlinkert** [comment]
> Do I remove old versions of node.js for unit tests?

No, we need them to pass.

**Comment by jonschlinkert** [comment]
@onokumus I completely forgot about this pr when I pushed up changes, very sorry. I like the changes you made, I think we would just need to lock the version of mocha to a version that doesn't depend on es6. 

Would you be willing to update the pr with the new code changes I made? thanks in advance, and again my apologies

**Comment by onokumus** [comment]
I'm working on.

**Pull request closed without merging**
