### PR TITLE
Added hooks support

### PR DESCRIPTION
**Pull request by def14nt**
Added support for hooks, meaning custom handlers can be added for passed values.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
I'm not sure that I like it that way. More clear and safe is how it was in the first commits with the `.register` thingy.

**Comment by tunnckoCore** [comment]
Hey @jonschlinkert @doowb check out this one ;p

**Comment by def14nt** [comment]
Check out the latest commit @tunnckoCore

**Comment by def14nt** [comment]
Hello?

**Comment by def14nt** [comment]
Welp, it's there if anyone wants to pull this.

**Comment by def14nt** [comment]
@tunnckoCore Is anyone going to actually answer this - instead of reacting like an idiot?

**Comment by def14nt** [comment]
I'd like to see some decisiveness here.

**Comment by tunnckoCore** [comment]
Don't push so hard. It's open source dude. I know it may sucks in such situations, but patience is the key. I glace looked over the commits before week and as i remember it's okey to me. I don't have any access to merge, publish, release and proceed. I don't know what's expected from me to do man - don't overreact - i can't do anything anyway.

**Comment by def14nt** [comment]
nah knock it on the head then mate, thanks

**Comment by jonschlinkert** [comment]
I didn't comment because I was busy widdling down the 140 other issues I had queued up before this one. This was a feature request, not a bug.

**Comment by tunnckoCore** [comment]
Then you definitely are not familiar with the community and how everything goes.
When I started and didn't have too much to do and I expected quick responses too.
I was excited and was refreshing like per 20-30 minutes - no results, and I was sad and was kinda angry and wondering what the heck is happening, is there something wrong and etc. But eventually, a few years passed and now I have tons of work to do so all this time is passing very fast.

I feel you, really, it still sucks to me too, because I have tons of issues and PRs opened out there without any response or progress. But from time to time I'm pinging and move on.

Not to mention that they are totally different things - reacting is a lot easier than writing meaningful review or comment. :D Anyway.

**Pull request closed without merging**
